### ISSUE TITLE
NPM support

### ISSUE THREAD

**Issue by IzaiahSun** [nascentxyz/pyrometer#20]
Hi, I notice that pyrometer would parse all the dependencies used by `import`. And in some projects, the dependencies may comes from npm or other package managers. If there is a need for support for import statements starts with "@", I can try to implement this and send a pull request to this repo.

There is an example
```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.9;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Votes.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import "../shared/ProtocolConstants.sol";

contract XVader is ProtocolConstants, ERC20Votes, ReentrancyGuard {
    // Address of vader token
    IERC20 public immutable vader;

    /*
     * @dev Initializes contract's state by setting vader's tokens address and
     * setting current token's name and symbol.
     **/
    constructor(IERC20 _vader)
        ERC20Permit("XVader")
        ERC20("XVader", "xVADER")
    {
        require(
            _vader != IERC20(_ZERO_ADDRESS),
            "XVader::constructor: _vader cannot be a zero address"
        );
        vader = _vader;
    }
......
```

**Comment by brockelmore** [comment]
You need to provide a `--remappings remappings.txt`. A good PR would be documenting this though, as well as updating the panic to suggest adding the remappings flag! (Please make sure you have the latest version and if you still have an issue let me know!)

**Comment by IzaiahSun** [comment]
Thanks a lot! It works!
